FILE_CONENT property proposal.
ShiftLeftSecurity/codepropertygraph pull request #1737
Opened 2023-10-17 10:01 UTC by ml86

2023-10-17 10:03 UTC, fabsx00 requested changes
Can we just call them `CONTENT`, `OFFSET`, ...?

2023-10-17 10:05 UTC, ml86 commented
We already have a CONTENT property which is used for CONFIG_FILE nodes. I did not want to reuse it to avoid confusion. As for the offsets: Yes, i can just name them OFFSET end OFFSET_END.

2023-10-17 12:36 UTC, ml86 commented
Ok, i now reuse the already existing CONTENT property.

2023-10-17 12:56 UTC, fabsx00 approved these changes

2023-10-18 12:06 UTC, johannescoetzee approved these changes

2023-10-18 12:06 UTC, merged