Stats logger interceptor
ShiftLeftSecurity/codepropertygraph pull request #1765
Opened 2024-04-09 17:05 UTC by pandurangpatil

Temporary mechanism to intercept the Passes and capture starting and ending events.

2024-04-11 06:33 UTC, DavidBakerEffendi approved these changes

2024-04-11 06:34 UTC, mpollmeier requested changes
please don't merge yet, I'll add some comments in a bit

2024-04-11 06:39 UTC, mpollmeier commented
Having the logger as a global object with mutable state seems like a bad idea, e.g. because we want to be able to run passes in parallel. 
Also, the `initialise` method isn't ever called, not sure how and if this even works...?

2024-04-11 07:01 UTC, DavidBakerEffendi commented on codepropertygraph/src/main/scala/io/shiftleft/utils/StatsCollector.scala
> +object StatsLogger extends DataLogger {
Why are we making this an object instead of a class that we can keep all fields immutable?

2024-04-13 17:06 UTC, pandurangpatil commented
@mpollmeier @DavidBakerEffendi this is an temporary arrangement I am making to get some urgent troubleshooting done on customer on premise setup. As I don't have access to customer code, I need to get this one pushed for time being quickly. I will make sure in few days to update the original PR which will address the previous PR comments.

2024-04-14 10:53 UTC, DavidBakerEffendi commented
@pandurangpatil Would it not make sense to then set up a local release on the customer's side? Or perhaps have a release for a Privado fork on this to benefit you guys in these situations long term?

2024-09-17 11:09 UTC, closed without merging